export enum FormBuilderActionType {
  SELECTED_FORM_COMPONENT = 'SELECTED_FORM_COMPONENT',
  SET_FORM_COMPONENTS = 'SET_FORM_COMPONENTS',
  UPDATE_FORM_COMPONENT = 'UPDATE_FORM_COMPONENT',
  DELETE_FORM_COMPONENT = 'DELETE_FORM_COMPONENT',

  SET_FORM_TITLE = 'SET_FORM_TITLE',
  SET_FORM_DETAILS = 'SET_FORM_DETAILS',
}
