export enum UsersActionType {
  FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST',
  FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE',
  SET_CHANGE_USER_PASSWORD = 'SET_CHANGE_USER_PASSWORD',
  RESET_CHANGE_USER_PASSWORD = 'RESET_CHANGE_USER_PASSWORD',
}
